[tool.pdm]

[tool.pdm.dev-dependencies]
dev = []

[tool.pdm.scripts]
cythonize = {cmd = "cythonize --3str -i scripts/cy_triangles.pyx", help = "compile `cy_triangles.pyx` with `cython`"}
mypyze = {shell = "cd scripts/ && mypyc my_triangles.pyx", help = "compile `my_triangles.pyx` with `mypyc`"}
compile = {composite = ["cythonize", "mypyze"]}

pypytime = {cmd = "time pypy3 -c 'from scripts.py_triangles import main; print(main())'", help = "time exec with `pypy3`", env = {FB_DATA = "data/facebook_combined.txt"}}
time = {cmd = "time python -c 'from scripts.{args}_triangles import main; print(main())'", help = "time exec with `python`: specify additional arg `py`, `my` or `cy` for Python, Mypy and Cython", env = {FB_DATA = "data/facebook_combined.txt"}}
# run-all = {composite = []}

[project]
authors         = [{name = "Murilo Cunha", email = "murilo@dataroots.io"}]
dependencies    = ["Cython>=3.0.0b3", "mypy>=1.3.0", "setuptools>=67.8.0"]
description     = ""
license         = {text = "MIT"}
name            = "python-speedups"
requires-python = ">=3.9"
version         = "0.0.0"
