[tool.pdm]

[tool.pdm.dev-dependencies]
dev = [
    "pip>=23.1.2",
]

[project]
authors = [{name = "Murilo Cunha", email = "murilo@dataroots.io"}]
dependencies = [
    "Cython>=3.0.0b3",
    "mypy>=1.3.0",
    "setuptools>=67.8.0",
    "maturin>=1.0.0",
]
description = ""
license = {text = "MIT"}
name = "python-speedups"
requires-python = ">=3.9"
version = "0.0.0"
