[tool.pdm]

[tool.pdm.dev-dependencies]
dev = ["pip>=23.1.2", "pre-commit>=3.3.3"]

[project]
authors = [{name = "Murilo Cunha", email = "murilo.k.s.cunha95@gmail.com"}]
dependencies = [
    "Cython>=3.0.0b3",
    "mypy>=1.3.0",
    "setuptools>=67.8.0",
    "maturin>=1.0.0",
]
description = ""
license = {text = "MIT"}
name = "faster-python-with-friends"
requires-python = ">=3.10"
version = "0.0.0"

[tool.ruff]
fix = true
force-exclude = true
ignore = ["EM", "D203", "D212"]
select = ["ALL"]
target-version = "py310"
